all:
  hosts:
    centos1:
      ansible_host: 192.168.1.170
      ip: 192.168.1.170
      access_ip: 192.168.1.170
      etcd_member_name: etcd1
    centos2:
      ansible_host: 192.168.1.171
      ip: 192.168.1.171
      access_ip: 192.168.1.171
    centos3:
      ansible_host: 192.168.1.172
      ip: 192.168.1.172
      access_ip: 192.168.1.172
    centos4:
      ansible_host: 192.168.1.173
      ip: 192.168.1.173
      access_ip: 192.168.1.173
    centos5:
      ansible_host: 192.168.1.174
      ip: 192.168.1.174
      access_ip: 192.168.1.174
  children:
    kube-master:
      hosts:
        centos1:
    kube-node:
      hosts:
        centos1:
        centos2:
        centos3:
        centos4:
        centos5:
    etcd:
      hosts:
        centos1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
